[master]
master ansible_host=172.31.65.147 ansible_user=nishan

[gpu]
worker1 ansible_host=172.31.65.144 ansible_user=kundan

[cpu]
worker2 ansible_host=172.31.65.111 ansible_user=gaurav

[workers:children]
gpu
cpu

[all:vars]
ansible_python_interpreter=/usr/bin/python3